print("Introduce a continuacion 5 palabras: ")
palabra1 = input("Primera palabra: ")
palabra2 = input("Segunda palabra: ")
palabra3 = input("Tercera palabra: ")
palabra4 = input("Cuarta palabra: ")
palabra5 = input("Quinta palabra: ")

print(f"{palabra1},")
print(f"{palabra2},")
print(f"{palabra3},")
print(f"{palabra4},")
print(f"{palabra5},")